networks:
  nginx_net:
    driver: bridge
    

services:
  app-01: &app
    build: .
    hostname: app-01
    networks:
      - nginx_net
  
  app-02:
    <<: *app
    hostname: app-02

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-01
      - app-02
    ports:
      - "80:80"
    
    networks:
      - nginx_net
  
  # db:
  #       container_name: biblia-backend-db
  #       image: postgres:15.4
  #       environment:
  #           POSTGRES_DB: biblia-backend-db
  #           POSTGRES_PASSWORD: postgres
  #           POSTGRES_USER: user
  #       volumes:
  #           - ./docker/postgres/postgres.conf:/etc/postgresql.conf
  #           - ./docker/postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
  #       command: 'postgres -c config_file="/etc/postgresql.conf" -c "max_connections=450"'
  #       network_mode: host